spring.application.name=sentinelpay-backend
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinelpay
spring.datasource.username=postgres
spring.datasource.password=newyorkcity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

